repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v16.0.6"
    hooks:
      - id: clang-format
        args: [--style=file]
        files: "\\.(c|cpp|cc|h|hpp)$"
